services:

  # frontend:
  #   build:
  #     context: ./front-end
  #   ports:
  #     - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/logs/requests.txt:/app/logs/requests.txt
      - ./backend/logs/dbcount.txt:/app/logs/dbcount.txt
    env_file:
      - .env
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: ["python", "worker.py"]
    depends_on:
      - backend
  
  # Three cache instances as shown in your diagram
  cache1:
    build: ./cache
    ports:
      - "8001:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
  
  cache2:
    build: ./cache
    ports:
      - "8002:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
  
  cache3:
    build: ./cache
    ports:
      - "8003:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
  
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/load-balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cache1
      - cache2
      - cache3

