version: '3'

services:
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/load-balancer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge