version: '3'

services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    networks:
      - app-network
  
  # Three cache instances as shown in your diagram
  cache1:
    build: ./cache
    ports:
      - "8001:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
  
  cache2:
    build: ./cache
    ports:
      - "8002:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
  
  cache3:
    build: ./cache
    ports:
      - "8003:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
  
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/load-balancer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - cache1
      - cache2
      - cache3

networks:
  app-network:
    driver: bridge